# Generated by scripts/render-packaging.sh. Do not edit by hand; edit the template.
class Svipall < Formula
  desc "Local-first web scraping and captcha MCP server for AI agents"
  homepage "https://github.com/ilien-dev/svipall"
  version "@VERSION@"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v@VERSION@/svipall-@VERSION@-aarch64-apple-darwin.tar.gz"
      sha256 "@SHA_AARCH64_APPLE_DARWIN@"
    end
    on_intel do
      url "https://github.com/ilien-dev/svipall/releases/download/v@VERSION@/svipall-@VERSION@-x86_64-apple-darwin.tar.gz"
      sha256 "@SHA_X86_64_APPLE_DARWIN@"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v@VERSION@/svipall-@VERSION@-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "@SHA_AARCH64_UNKNOWN_LINUX_GNU@"
    end
    on_intel do
      url "https://github.com/ilien-dev/svipall/releases/download/v@VERSION@/svipall-@VERSION@-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "@SHA_X86_64_UNKNOWN_LINUX_GNU@"
    end
  end

  def install
    bin.install "svipall"
    bin.install "svipall-mcp"
    doc.install "README.md"
    # The agent skill, next to the binaries it documents, where an agent can be pointed at it.
    pkgshare.install "SKILL.md"
  end

  def caveats
    <<~EOS
      Browser tiers need a Chromium-based browser. Either install Chrome or Edge, or let
      svipall keep one of its own (~190 MB):

        svipall browser install

      Then check what this installation can do:

        svipall doctor

      To use it from Claude Code:

        claude mcp add svipall -- svipall-mcp
    EOS
  end

  test do
    assert_match "\"version\": \"#{version}\"", shell_output("#{bin}/svipall --version")
    assert_match "\"problems\"", shell_output("#{bin}/svipall doctor")
  end
end
